# Параметры релиза
release:
  name: sidecar-injector
  namespace: prod

nameOverride: ""
fullnameOverride: ""

volumes:
  - name: tls-certs
    secret:
      secretName: sidecar-injector-tls

# Основные настройки
image: nginx:alpine
containerPort: 8080

certManager:
  enabled: true
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

# Добавляем настройки для RBAC
rbac:
  create: true
  serviceAccount:
    create: true
    name: ""

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: sidecar-injector.prod.local
    paths:
    - path: /
      pathType: Prefix

sidecar:
  image: nginx:alpine
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi
  
  ingressSidecar:
    enabled: true
    port: 8443
    containerPort: 8443
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    config: |
      server {
          listen 8443;
          server_name localhost;
          location / {
              proxy_pass http://localhost:8080;
          }
      }
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/tls
      readOnly: true
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf

  egressSidecar:
    enabled: true
    port: 8444
    containerPort: 8444
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    config: |
      server {
          listen 8444;
          server_name localhost;
          location / {
              proxy_pass http://localhost:8080;
          }
      }
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/tls
      readOnly: true
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf

