{{- if and .Values.clusterIssuer.enabled (eq .Values.clusterIssuer.type "letsencrypt") .Values.cloudflare.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: {{ .Values.release.namespace }}
type: Opaque
data:
  api-token: {{ .Values.cloudflare.apiToken | b64enc }}
{{- end }}