#!/usr/bin/bash
ln -s /usr/bin/cert-manager    $(pwd)/cert-manager    >  /dev/null
ln -s /usr/bin/local-ca        $(pwd)/local-ca        >  /dev/null
ln -s /usr/bin/ollama          $(pwd)/ollama          >  /dev/null
ln -s /usr/bin/open-webui      $(pwd)/open-webui      >  /dev/null
ln -s /usr/bin/sidecarinjector $(pwd)/sidecarinjector >  /dev/null

ln -s /usr/bin/deploy-all      $(pwd)/deploy-all      >  /dev/null
ln -s /usr/bin/git-update      $(pwd)/git-update      >  /dev/null

