# Параметры релиза
release:
  name: cert-manager
  namespace: prod

cert-manager:
  installCRDs: true
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Настройки для ClusterIssuer
clusterIssuer:
  enabled: true
  name: selfsigned-issuer
  type: selfsigned
  commonName: "*.prod.local"
  dnsNames:
    - "*.prod.local"
    - "prod.local"
    - "eberil.ru"
  duration: "8760h" # 1 год
  renewBefore: "720h" # 30 дней