ingress-nginx:
  controller:
    hostPort:
      enabled: true
    service:
      type: NodePort
      ports:
        http: 80
        https: 443
      nodePorts:
        http: 30080
        https: 30443
    watchIngressWithoutClass: true
    nodeSelector:
      ingress-ready: "true"
    publishService:
      enabled: true
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    admissionWebhooks:
      enabled: true
      port: 8443
      service:
        ports:
          webhook: 8443
        nodePort: 30444
      certManager:
        enabled: true
        rootCert:
          issuerRef:
            name: eberil-ru-issuer
            kind: ClusterIssuer
        admissionCert:
          issuerRef:
            name: eberil-ru-issuer
            kind: ClusterIssuer
    extraArgs:
      publish-status-address: localhost
      enable-ssl-passthrough: "true"
    terminationGracePeriodSeconds: 300
    minReadySeconds: 0
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
    config:
      ssl-redirect: "false"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      use-proxy-protocol: "false"