# Параметры релиза
release:
  name: open-webui
  namespace: prod

# Основные настройки приложения
image:
  repository: ghcr.io/open-webui/open-webui
  tag: "latest"
  pullPolicy: Always
  pullSecrets: []

# Настройки развертывания
deployment:
  replicas: 1
  gpuConfig: true
  resources:
    limits:
      cpu: "3000m"
      memory: "4Gi"
    requests:
      cpu: "2000m"
      memory: "2Gi"
  env:
    - name: MODEL
      value: "deepseek-r1:14b-qwen-distill-q4_K_M"
    - name: DEBUG
      value: "false"
    - name: ENABLE_MEMORY_REDUCTION
      value: "true"
    - name: COMPUTE_SHAPES
      value: "false"
    - name: MAX_PARALLEL_REQUESTS
      value: "1"
    - name: NODE_OPTIONS
      value: "--max-old-space-size=4096 --max-http-header-size=32768"
    - name: ENABLE_AGGRESSIVE_GC
      value: "true"
    - name: OLLAMA_API_BASE
      value: "http://ollama.prod.svc.cluster.local:11434/api"
    - name: OLLAMA_BASE_URL
      value: "http://ollama.prod.svc.cluster.local:11434"
    - name: OLLAMA_HOST
      value: "ollama.prod.svc.cluster.local"
    - name: OLLAMA_PORT
      value: "11434"
    - name: DISABLE_TELEMETRY
      value: "true"
    - name: HEALTH_CHECK_ENABLED
      value: "true"
    - name: HEALTH_CHECK_PATH
      value: "/health"
    - name: WEB_CONCURRENCY
      value: "1"
    - name: WORKERS_PER_CORE
      value: "1"
    - name: PORT
      value: "3000"
    - name: HOST
      value: "0.0.0.0"
    - name: TIMEOUT
      value: "1200"
    - name: GRACEFUL_TIMEOUT
      value: "1200"
    - name: KEEP_ALIVE
      value: "1200"
    - name: UNICORN_ENABLED
      value: "true"
    - name: UVICORN_WORKERS
      value: "1"
    - name: UVICORN_HOST
      value: "0.0.0.0"
    - name: UVICORN_PORT
      value: "3000"
    - name: UVICORN_TIMEOUT
      value: "1200"
    - name: NGINX_MAX_UPLOAD_SIZE
      value: "100m"
    - name: NGINX_PROXY_TIMEOUT
      value: "1200s"
    - name: CHUNK_SIZE
      value: "512"
    - name: STREAM_CHUNK_SIZE
      value: "512"
    - name: MAX_CONTEXT_WINDOW_SIZE
      value: "32768"

# Секреты
secrets:
  openai:
    apiKey: ""
    apiBase: ""
  ollama:
    apiBase: "http://ollama.prod.svc.cluster.local:11434/api"
  custom: {}

# Настройки сервиса
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  annotations: {}
  labels: {}

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/websocket-services: "{{ .Release.Name }}"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: webui.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: eberil-ru-tls
      hosts:
        - webui.prod.local

# TLS Configuration
tls:
  enabled: true
  certificate: "" # Base64 encoded certificate (PEM format)
  key: ""         # Base64 encoded private key (PEM format)

persistence:
  enabled: true
  size: 20Gi
  storageClass: ""
  useHostPath: false
  hostPath: "/mnt/u"