apiVersion: v1
kind: Secret
metadata:
  name: eberil-ru-tls
  namespace: prod
type: kubernetes.io/tls
data:
  # These values should be replaced with the actual base64-encoded certificate and key
  tls.crt: ${CERTIFICATE}
  tls.key: ${PRIVATE_KEY}