apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-coredns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coredns.labels" . | nindent 4 }}
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        import /etc/coredns/prod.local.server
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache {
           success 10800
           denial 3600
        }
        loop
        reload
        loadbalance
    }