kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Add ulimit settings to address "too many open files" issue
featureGates:
  EphemeralContainers: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true,nvidia.com/gpu=true"
        feature-gates: "DevicePlugins=true"
    skipPhases:
      - preflight
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        feature-gates: "DevicePlugins=true"
  extraMounts:
  - hostPath: /usr/lib/wsl/lib
    containerPath: /usr/lib/wsl/lib
  - hostPath: /usr/bin/nvidia-smi
    containerPath: /usr/bin/nvidia-smi
  - hostPath: /usr/lib/x86_64-linux-gnu
    containerPath: /usr/lib/x86_64-linux-gnu
  - hostPath: /usr/local/cuda/lib64
    containerPath: /usr/local/cuda/lib64
    readOnly: true
    propagation: None
  - hostPath: /usr/local/cuda/include
    containerPath: /usr/local/cuda/include
    readOnly: true
    propagation: None
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "nvidia.com/gpu=true"
        feature-gates: "DevicePlugins=true"
    skipPhases:
      - preflight
  extraMounts:
  - hostPath: /usr/lib/wsl/lib
    containerPath: /usr/lib/wsl/lib
  - hostPath: /usr/bin/nvidia-smi
    containerPath: /usr/bin/nvidia-smi
  - hostPath: /usr/lib/x86_64-linux-gnu
    containerPath: /usr/lib/x86_64-linux-gnu
  - hostPath: /usr/local/cuda/lib64
    containerPath: /usr/local/cuda/lib64
    readOnly: true
    propagation: None
  - hostPath: /usr/local/cuda/include
    containerPath: /usr/local/cuda/include
    readOnly: true
    propagation: None