#!/usr/bin/bash

# DevOps Banner
devops_banner() {
cat << "EOF"
#  ____             ___              
# |  _ \  _____   _/ _ \ _ __  ___  
# | | | |/ _ \ \ / / | | | '_ \/ __| 
# | |_| |  __/\ V /| |_| | |_) \__ \ 
# |____/ \___| \_/  \___/| .__/|___/ 
#                        |_|          
#                     by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Because DevOps is about sharing and caring"
EOF
}

# Deploy Banner
deploy_banner() {
cat << "EOF"
#  ____             _             
# |  _ \  ___ _ __ | | ___  _   _ 
# | | | |/ _ \ '_ \| |/ _ \| | | |
# | |_| |  __/ |_) | | (_) | |_| |
# |____/ \___| .__/|_|\___/ \__, |
#            |_|            |___/ 
#                         by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Time to ship some containers!"
EOF
}

# Kubernetes Banner
k8s_banner() {
cat << "EOF"
#  _  _____ ____  
# | |/ / _ \___ \ 
# | ' / (_) |__) |
# | . \> _ </ __/ 
# |_|\_\___/_____|
#            by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Because clusters should be fun!"
EOF
}

# Production Banner
production_banner() {
cat << "EOF"
# _    _ _    _ _          _  __      _    _ _    _ _          _  __ 
#| |  | | |  | | |   /\   | |/ /     | |  | | |  | | |   /\   | |/ / 
#| |__| | |  | | |  /  \  | ' /      | |__| | |  | | |  /  \  | ' / 
#|  __  | |  | | | / /\ \ |  <       |  __  | |  | | | / /\ \ |  <  
#| |  | | |__| | |/ ____ \| . \      | |  | | |__| | |/ ____ \| . \ 
#|_|  |_|\____/|_/_/    \_\_|\_\     |_|  |_|\____/|_/_/    \_\_|\_\
#                                                           by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# HUJAK-HUJAK PRODUCTION PRESENTS...
# "When you need to deploy but don't want to cry"
EOF
}

# Error Banner
error_banner() {
cat << "EOF"
#  _____ ____  ____   ___  ____  
# | ____|  _ \|  _ \ / _ \|  _ \ 
# |  _| | |_) | |_) | | | | |_) |
# | |___|  _ <|  _ <| |_| |  _ < 
# |_____|_| \_\_| \_\\___/|_| \_\
#                       by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Even errors can be stylish!"
EOF
}

# Success Banner
success_banner() {
cat << "EOF"
#  ____  _   _  ____ ____ _____ ____ ____  
# / ___|| | | |/ ___/ ___| ____/ ___/ ___| 
# \___ \| | | | |  | |   |  _| \___ \___ \ 
#  ___) | |_| | |__| |___| |___ ___) |__) |
# |____/ \___/ \____\____|_____|____/____/ 
#                                by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Mission accomplished with style!"
EOF
}

# Charts Banner
charts_banner() {
cat << "EOF"
#   _____ _                _       
#  / ____| |              | |      
# | |    | |__   __ _ _ __| |_ ___ 
# | |    | '_ \ / _` | '__| __/ __|
# | |____| | | | (_| | |  | |_\__ \
#  \_____|_| |_|\__,_|_|   \__|___/
#                         by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Making Helm less scary since 2024!"
EOF
}

# Eberil Banner
eberil_banner() {
cat << "EOF"
#  _____ ____  _____ ____  ___ _     
# | ____|  _ \| ____|  _ \|_ _| |    
# |  _| | |_) |  _| | |_) || || |    
# | |___|  _ <| |___|  _ < | || |___ 
# |_____|_| \_\_____|_| \_\___|_____|
#                         by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Code like nobody's watching!"
EOF
}

# Coffee Break Banner
coffee_banner() {
cat << "EOF"
#   _____ ___  _____ _____ _____ _____ 
#  / ____/ _ \|  ___|  ___|  ___|  ___|
# | |   | | | | |_  | |_  | |_  | |_   
# | |   | | | |  _| |  _| |  _| |  _|  
# | |___| |_| | |   | |   | |   | |    
#  \_____\___/|_|   |_|   |_|   |_|    
#                         by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Time for coffee and kubectl get pods"
EOF
}

# Debug Banner
debug_banner() {
cat << "EOF"
#  ____  _____ ____  _   _  ____ 
# |  _ \| ____|  _ \| | | |/ ___|
# | | | |  _| | |_) | | | | |  _ 
# | |_| | |___|  _ <| |_| | |_| |
# |____/|_____|_| \_\\___/ \____|
#                     by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "When in doubt, add more print statements!"
EOF
}

# YAML Banner
yaml_banner() {
cat << "EOF"
#  __     ___    __  __ _     
#  \ \   / / \  |  \/  | |    
#   \ \ / / _ \ | |\/| | |    
#    \ V / ___ \| |  | | |___ 
#     \_/_/   \_\_|  |_|_____|
#                   by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Indentation is not just a style, it's a way of life!"
EOF
}

# DevOps Life Banner
devops_life_banner() {
cat << "EOF"
#  ____             ___              _     _  __       
# |  _ \  _____   _/ _ \ _ __  ___  | |   (_)/ _| ___ 
# | | | |/ _ \ \ / / | | | '_ \/ __| | |   | | |_ / _ \
# | |_| |  __/\ V /| |_| | |_) \__ \ | |___| |  _|  __/
# |____/ \___| \_/  \___/| .__/|___/ |_____|_|_|  \___|
#                        |_|            by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Git push and pray: The DevOps way!"
EOF
}

# Panic Banner
panic_banner() {
cat << "EOF"
#  ____   _    _   _ ___ ____ 
# |  _ \ / \  | \ | |_ _/ ___|
# | |_) / _ \ |  \| || | |    
# |  __/ ___ \| |\  || | |___ 
# |_| /_/   \_\_| \_|___\____|
#                   by @ӗberil
#
# Copyright (c) 2024 Mikhail Eberil
# This code is free! Share it, spread peace and technology!
# "Keep calm and kubectl delete -f panic.yaml"
EOF
}