# Параметры релиза
release:
  name: ollama
  namespace: prod

# Основные настройки приложения
image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

# Настройки развертывания
deployment:
  replicas: 1
  resources:
    limits:
      cpu: "12"
      memory: "24Gi"
      nvidia.com/gpu: "1"
    requests:
      cpu: "8"
      memory: "16Gi"
  envFrom:
    - configMapRef:
        name: gpu-config
  env:
    - name: OLLAMA_HOST
      value: "0.0.0.0"
    - name: OLLAMA_COMPUTE_TYPE
      value: "gpu"
    - name: OLLAMA_GPU_LAYERS
      value: "99"  # Use all layers on GPU for maximum performance
    - name: OLLAMA_F16
      value: "true"
    - name: OLLAMA_MODEL
      value: "deepseek-r1:32b-q4_0"  # Use 4-bit quantization for better performance
    - name: OLLAMA_QUANTIZATION
      value: "q4_0"  # 4-bit quantization
    - name: OLLAMA_CUDA_MEMORY_FRACTION
      value: "0.95"  # Use 95% of GPU memory
    - name: OLLAMA_CUDA_FORCE_ALLOCATION
      value: "true"  # Force memory allocation

# Настройки сервиса
service:
  type: NodePort
  port: 11434
  targetPort: 11434
  nodePort: 30434

# Настройки Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: ollama.prod.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ollama-tls
      hosts:
        - ollama.prod.local

# Настройки хранилища для моделей
persistence:
  enabled: true
  size: 100Gi  # Increased storage for larger models
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Настройки безопасности
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Настройки сети
networkPolicy:
  enabled: true
  allowedNamespaces:
    - prod