{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "sidecar-injector.fullname" . }}-cert
  namespace: {{ .Values.release.namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: {{ include "sidecar-injector.fullname" . }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "DevSecMLOps"
  commonName: {{ include "sidecar-injector.fullname" . }}.{{ .Values.release.namespace }}.svc
  dnsNames:
    - {{ include "sidecar-injector.fullname" . }}.{{ .Values.release.namespace }}.svc
    - {{ include "sidecar-injector.fullname" . }}.{{ .Values.release.namespace }}.svc.cluster.local
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
