apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca-selfsigned-issuer
  namespace: {{ .Values.release.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: {{ .Values.release.namespace }}
spec:
  isCA: true
  commonName: {{ .Values.ca.commonName }}
  secretName: {{ .Values.ca.secretName }}
  duration: {{ .Values.ca.validityDuration }}
  renewBefore: {{ .Values.ca.renewBefore }}
  subject:
    organizations:
      - {{ .Values.ca.organization }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: local-ca-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca-issuer
  namespace: {{ .Values.release.namespace }}
spec:
  ca:
    secretName: {{ .Values.ca.secretName }}