apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.release.namespace }}
  labels:
    app: ollama
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      {{- if .Values.deployment.gpuNodeSelector.enabled }}
      nodeSelector:
        {{ .Values.deployment.gpuNodeSelector.labelKey }}: {{ .Values.deployment.gpuNodeSelector.labelValue | quote }}
      {{- end }}
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      containers:
        - name: ollama
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PATH
              value: "/usr/lib/wsl/lib:/usr/local/nvidia/bin:/usr/local/cuda/bin:$(PATH)"
            - name: LD_LIBRARY_PATH
              value: "/usr/lib/wsl/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:$(LD_LIBRARY_PATH)"
            {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.deployment.envFrom }}
            {{- toYaml .Values.deployment.envFrom | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
            - name: ollama-data
              mountPath: /mnt/o
            - name: nvidia-wsl
              mountPath: /usr/lib/wsl/lib
      volumes:
        - name: ollama-data
          hostPath:
            path: /mnt/o
        - name: nvidia-wsl
          hostPath:
            path: /usr/lib/wsl/lib
        - name: nvidia-capabilities
          hostPath:
            path: /usr/lib/wsl/lib/nvidia/capabilities