apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-config
  namespace: {{ .Values.release.namespace }}
data:
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
  MAX_PARALLEL_REQUESTS: "4"
  CUDA_MEMORY_FRACTION: "0.95"