apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nvidia-config
  namespace: {{ .Values.release.namespace }}
data:
  config: |
    {
      "default-runtime": "nvidia",
      "runtimes": {
        "nvidia": {
          "path": "/usr/bin/nvidia-container-runtime",
          "runtimeArgs": []
        }
      }
    }