{{- if and .Values.tls.certificate .Values.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Values.release.namespace }}
  labels:
    app: open-webui
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}