apiVersion: v2
name: ingress-nginx
description: "NGINX Ingress Controller for Kubernetes"
type: application
version: 1.0.0
appVersion: "1.9.4"
maintainers:
  - name: "Mikhail Eberil"
    email: "eberil@example.com"
dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"