apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        hosts {
            ${OLLAMA_IP} ollama.prod.local
            ${WEBUI_IP} webui.prod.local
            ${INGRESS_IP} dashboard.prod.local
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache {
           success 10800
           denial 3600
        }
        loop
        reload
        loadbalance
    }